services:
  db:
    image: "postgres:13.1"
    restart: always
    env_file:
      - test.env
    ports:
      - "5432:5432"
    volumes:
      - ./containers/postgres/data:/var/lib/postgresql
    healthcheck:
      test: CMD-SHELL pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    env_file:
      - test.env

    depends_on:
      - db

    ports:
      - "8000:8000"

    command: bash -c "aerich upgrade &&  uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 "
